// ============================================================
// SKILLFORGE AI — Curated Recommended Topics
// Every activity has its own dedicated, non-overlapping list.
// DO NOT add a fallback that returns another activity's topics.
// ============================================================

export const recommendedTopics = {

  // ── JAM SESSION ─────────────────────────────────────────────────────────────
  // Short, speakable topics for 1-2 minute spontaneous speech
  jam: [
    "Artificial Intelligence: Boon or Threat?",
    "Social Media and Its Impact on Students",
    "Life Without Smartphones",
    "Is Technology Making Us Lazy?",
    "The Future of Artificial Intelligence",
    "Online Education vs Offline Education",
    "Importance of Time Management",
    "Work-Life Balance in the Modern Era",
    "Success vs Happiness",
    "Money vs Passion",
    "Is Failure Necessary for Success?",
    "The Importance of Communication Skills",
    "Should Students Use AI Tools?",
    "Future of Jobs in the AI Era",
    "Technology and Human Relationships",
    "Climate Change: Our Shared Responsibility",
    "Importance of Leadership",
    "Teamwork vs Individual Performance",
    "Discipline vs Motivation",
    "Impact of Video Games on Youth",
    "The Importance of Mental Health Awareness",
    "Is Privacy Dead in the Digital Age?",
    "Role of Ethics in Business",
    "Electric Vehicles: The Future of Mobility",
    "Importance of Creativity in Education",
    "Smart Cities: Dream or Reality?",
    "Is Higher Education Worth It?",
    "The Power of Positive Thinking",
    "Importance of Financial Literacy",
    "Space Exploration: Necessity or Waste?",
    "The Importance of Reading Books",
    "Influence of Cinema on Society",
    "Stress Management Strategies",
    "Overcoming Public Speaking Fear",
    "Youth and Nation Building",
    "Importance of Voting in a Democracy",
    "Role of Women in Modern Society",
    "India in 2050: A Vision",
    "Is Social Media Ruining Attention Spans?",
    "Importance of Sports in Student Life",
    "Should Animals Be Used in Scientific Research?",
    "Impact of Globalization on Indian Culture",
    "The Gig Economy: Freedom or Exploitation?",
    "Artificial Intelligence in Healthcare",
    "Internet of Things: The Connected Future",
    "Brain Drain vs Brain Gain",
    "Peer Pressure: Good or Bad?",
    "The Future of Print Media"
  ],

  // ── SELF INTRODUCTION ────────────────────────────────────────────────────────
  // Interview-style self-introduction prompts — NOT debate or GD topics
  selfIntroduction: [
    "Tell me about yourself.",
    "Introduce yourself briefly.",
    "Tell me about your educational background.",
    "What are your core strengths?",
    "What is your biggest weakness and how are you working on it?",
    "What are your career goals?",
    "Where do you see yourself in five years?",
    "Why should we hire you?",
    "What are your hobbies and interests outside academics?",
    "Tell me about your most significant academic achievement.",
    "Tell me about your most important project.",
    "What motivates you to give your best?",
    "What are your short-term goals?",
    "What are your long-term career goals?",
    "Describe yourself in three words and explain each.",
    "What makes you different from other candidates?",
    "How do you handle failure or setbacks?",
    "Tell me about a time you demonstrated leadership.",
    "Describe your ideal work environment.",
    "Why did you choose your field of study?",
    "What skills are you currently trying to develop?",
    "How do you prioritize tasks during a busy schedule?",
    "What does success mean to you personally?",
    "Tell me about a challenge you resolved on your own.",
    "How do you manage stress during tight deadlines?",
    "Who is your role model and what have you learned from them?",
    "What is the most creative project you have ever completed?",
    "Tell me about a time you had to adapt to sudden change.",
    "What are your expectations from your first job?",
    "Describe a time when you went beyond what was expected.",
    "How do you respond to constructive criticism?",
    "What extracurricular activities have shaped your personality?",
    "What is your biggest professional or academic accomplishment?",
    "Tell me about your communication style.",
    "How do you ensure continuous learning in your field?",
    "Describe a situation where you had to work under pressure.",
    "What three skills do you bring to this role?",
    "How do you handle disagreements with peers or teammates?",
    "What aspect of your personality makes you a good team player?",
    "Tell me why you are passionate about your chosen career.",
    "Describe a time you turned a failure into a learning experience.",
    "What is one thing you want to improve about yourself?",
    "How would your friends or professors describe you?",
    "What has been the most challenging course in your degree and how did you manage it?",
    "Tell me about a time you had to meet a strict deadline."
  ],

  // ── INTERVIEW PRACTICE ───────────────────────────────────────────────────────
  // HR, behavioral, situational — different from Self Introduction prompts
  interview: [
    "Walk me through your resume from start to finish.",
    "Why should our organization hire you over other candidates?",
    "Why do you want to work specifically for our company?",
    "What are your top three professional strengths?",
    "Describe your greatest weakness and your improvement plan.",
    "Tell me about a major challenge you faced and how you overcame it.",
    "Give an example of a time you collaborated successfully in a team.",
    "How do you manage pressure and multiple competing deadlines?",
    "Describe how you have handled a failure or disappointing outcome.",
    "Where do you see your career in five years?",
    "Tell me about your most complex technical or academic project.",
    "How do you handle disagreement with a manager or senior colleague?",
    "Describe your leadership experience and style.",
    "Give an example of a complex problem you solved creatively.",
    "Why did you choose this career path over other options?",
    "What do you know about our company's mission and culture?",
    "Tell me about a time you had to learn a new skill rapidly.",
    "How do you balance multiple priorities when everything is urgent?",
    "Describe a time you had to make an unpopular but correct decision.",
    "What are your salary expectations for this role?",
    "Tell me about constructive feedback you received and acted on.",
    "What does an ideal team look like to you?",
    "How do you ensure accuracy and high quality in your work?",
    "Describe a time you had to motivate a discouraged teammate.",
    "What are the most important qualities of a strong professional?",
    "Tell me about a situation where you had to compromise.",
    "How do you manage stress outside of professional commitments?",
    "Why are you looking to change your current role or domain?",
    "What is your approach to breaking down a complex technical concept?",
    "Describe a project that failed and the lessons you took from it.",
    "How do you stay focused during lengthy or repetitive work?",
    "Tell me about a time you took initiative without being asked.",
    "Are you comfortable working overtime when critical deadlines arise?",
    "How do you handle requirements that are vague or constantly changing?",
    "What is the most difficult decision you have made this year?",
    "Describe a time when your team disagreed on an important technical approach.",
    "How do you keep your technical skills current?",
    "Tell me about a time you gave feedback that improved someone's work.",
    "How do you build trust with a new team or manager?",
    "Do you have any questions for us about this role or our company?"
  ],

  // ── STORYTELLING ─────────────────────────────────────────────────────────────
  // Scenario-based narrative prompts
  storytelling: [
    "Tell a story about a difficult situation you overcame.",
    "Share a story about an unexpected act of kindness you witnessed.",
    "Tell a story about a time you took a calculated risk that paid off.",
    "Share an experience about visiting an unfamiliar city or place.",
    "Tell a story about a childhood memory that shaped your values.",
    "Narrate a story about a day when everything went wrong.",
    "Tell a story about achieving a meaningful goal against all odds.",
    "Share a story about a mentor who changed your perspective on life.",
    "Tell a story about finding a creative solution to a simple problem.",
    "Narrate an event where you had to adapt to a sudden change.",
    "Tell a story about learning a valuable lesson from a stranger.",
    "Share a story about a time you stood up for what you believed in.",
    "Tell a story about a collaborative victory with your team or friends.",
    "Narrate an amusing incident that happened to you recently.",
    "Tell a story about discovering a new passion or hobby.",
    "Share a story about overcoming a deep-seated fear.",
    "Tell a story about a project you poured your heart into.",
    "Narrate a story about finding unexpected inspiration.",
    "Tell a story about a conflict in a team that was resolved positively.",
    "Share a story about a miscommunication that turned out to be humorous.",
    "Tell a story about learning something new and applying it immediately.",
    "Narrate an adventure that pushed you out of your comfort zone.",
    "Tell a story about a small effort you made that had a big positive impact.",
    "Share a story about a tradition or cultural celebration you cherish.",
    "Tell a story about a moment you had to perform under unexpected pressure.",
    "Narrate a story about an outcome that surprised everyone including you.",
    "Tell a story about practicing patience in a difficult situation.",
    "Share a story about a dream or ambition that eventually came true.",
    "Tell a story about technology failing you at the worst possible moment.",
    "Narrate a story about a mystery or problem you helped solve.",
    "Tell a story about a hard lesson you only understood much later.",
    "Share a story about a person who changed your outlook on life.",
    "Tell a story about overcoming stage fright or public speaking anxiety.",
    "Narrate a story about a celebration that brought a community together.",
    "Tell a story about a time you had to let go of something important.",
    "Share a story about an unexpected friendship you formed.",
    "Tell a story about a moment you realized you had truly grown.",
    "Narrate a story about helping someone navigate a difficult time.",
    "Tell a story about discovering your true strength in a crisis.",
    "Share a story about a book, film, or conversation that changed your thinking."
  ],

  // ── IMPROMPTU SPEAKING ────────────────────────────────────────────────────────
  // Thought-provoking topics with 30-second prep time
  impromptu: [
    "Technology in Education: Blessing or Curse?",
    "The Importance of Self-Discipline",
    "Artificial Intelligence and Creative Writing",
    "Should Examinations Be Abolished?",
    "Global Warming: Time for Urgent Action",
    "The Impact of Remote Work on Society",
    "Is Social Media Making Us Less Social?",
    "The Role of Sports in Character Building",
    "Is Failure Really the Pillar of Success?",
    "The Future of Renewable Energy Sources",
    "Should Voting Be Made Compulsory?",
    "The Power of Visual Communication",
    "Is Space Exploration Worth the Cost?",
    "The Importance of Soft Skills in Professional Life",
    "Online Shopping vs Offline Retail",
    "The Role of Innovation in Industry Growth",
    "Should Mobile Phones Be Allowed in Classrooms?",
    "The Importance of Financial Planning for Youth",
    "Impact of Junk Food on the Younger Generation",
    "Is Reading Books Better Than Watching Movies?",
    "The Power of Empathetic Leadership",
    "Should Plastic Bags Be Banned Globally?",
    "The Impact of Music on Human Mood and Productivity",
    "Ethics in Modern Advertising",
    "Should College Education Be Free for All?",
    "The Rise of E-Commerce and Digital Payments",
    "The Importance of Mental Well-Being at the Workplace",
    "Is Corporate Social Responsibility Just a PR Exercise?",
    "The Future of Smart Homes and IoT Devices",
    "The Importance of Preserving Cultural Heritage",
    "Should Animal Testing Be Banned Entirely?",
    "The Role of Youth in Combating Climate Change",
    "The Impact of Tourism on Local Cultures",
    "Is Electric Mobility Ready for the Indian Market?",
    "The Importance of Work-Life Harmony",
    "Should Junk Food Be Taxed Heavily?",
    "The Power of Collaborative Problem Solving",
    "Is Cryptocurrency the Future of Finance?",
    "The Importance of Practising Cyber Hygiene",
    "The Role of Art and Culture in Modern Society",
    "Should Social Media Platforms Be Regulated by the Government?",
    "How Has the Pandemic Changed How We Work Forever?",
    "Is Minimalism the Answer to Modern Stress?",
    "The Importance of Learning a Second Language",
    "Should Professional Athletes Serve as Role Models?"
  ],

  // ── COMMUNICATION PRACTICE ────────────────────────────────────────────────────
  // Real-world workplace and social communication scenarios
  communication: [
    "Explaining a complex project update to a non-technical manager.",
    "Negotiating a deadline extension with a demanding client.",
    "Providing constructive feedback to a teammate without causing conflict.",
    "Addressing a misunderstanding that arose during a team meeting.",
    "Summarizing your quarterly achievements during a performance review.",
    "Pitching a new product or service idea to your team.",
    "De-escalating a tense conversation with a dissatisfied customer.",
    "Collaborating across cultural boundaries in an international team.",
    "Reporting a critical bug to a non-technical stakeholder clearly.",
    "Giving balanced performance feedback in a peer review.",
    "Requesting mentorship from a senior professional.",
    "Proposing a workflow improvement to increase team efficiency.",
    "Facilitating a brainstorming session effectively.",
    "Onboarding a new team member and explaining team norms.",
    "Responding constructively to negative feedback on your work.",
    "Presenting data insights to senior leadership.",
    "Persuading resistant colleagues to adopt a new process.",
    "Explaining a technical decision in a product strategy meeting.",
    "Communicating project risks to a project manager.",
    "Motivating your team after a setback or project cancellation.",
    "Asking for additional resources to complete a critical project.",
    "Leading a status-update call with multiple stakeholders.",
    "Handling an urgent cross-department coordination issue.",
    "Discussing an ethical concern with your manager professionally.",
    "Explaining a regulatory compliance requirement to the engineering team.",
    "Pitching yourself for a promotion during a one-on-one meeting.",
    "Communicating boundary-setting professionally to a colleague.",
    "Summarising key takeaways from a long workshop or training.",
    "Introducing a guest speaker at a corporate event.",
    "Handling a question you don't know the answer to in a presentation.",
    "Bridging communication gaps between a design team and developers.",
    "Following up professionally after an unanswered email.",
    "Communicating an unpopular policy change to your department.",
    "Giving a short daily stand-up update clearly and concisely.",
    "Discussing workload concerns with your team lead.",
    "Expressing gratitude and appreciation to a team professionally.",
    "Articulating your career development goals to your HR partner.",
    "Communicating user feedback to the product development team.",
    "Explaining a data privacy incident to business stakeholders.",
    "Presenting a post-mortem analysis after a system outage."
  ],

  // ── VOCABULARY PRACTICE ───────────────────────────────────────────────────────
  // Scenarios that challenge rich word choice and formal language
  vocabulary: [
    "Expressing polite disagreement in a professional business discussion.",
    "Describing the advantages of a sustainable business model.",
    "Articulating the importance of corporate governance and accountability.",
    "Explaining the concept of emotional intelligence in the workplace.",
    "Describing the impact of strategic leadership on organisational growth.",
    "Articulating the benefits of a diverse and inclusive work culture.",
    "Explaining the significance of effective time management strategies.",
    "Describing the role of critical thinking in professional decision-making.",
    "Articulating the consequences of poor communication in a team.",
    "Explaining how adaptability drives success in a volatile market.",
    "Describing the characteristics of an ethical organisational culture.",
    "Articulating the importance of continuous professional development.",
    "Explaining the value of constructive feedback in team settings.",
    "Describing the relationship between innovation and competitive advantage.",
    "Articulating the importance of transparency in leadership.",
    "Explaining the concept of work-life balance in modern organisations.",
    "Describing the role of resilience in overcoming professional setbacks.",
    "Articulating the value of cross-functional collaboration.",
    "Explaining the significance of accountability in team projects.",
    "Describing how empathy improves customer satisfaction.",
    "Articulating the distinction between leadership and management.",
    "Explaining the impact of globalisation on business practices.",
    "Describing the role of data-driven decision-making in business.",
    "Articulating the importance of stakeholder communication.",
    "Explaining the concept of professional integrity.",
    "Describing how strategic communication builds brand trust.",
    "Articulating the benefits of mentorship and knowledge transfer.",
    "Explaining the role of soft skills in career advancement.",
    "Describing the challenges of managing a geographically dispersed team.",
    "Articulating how psychological safety improves team performance.",
    "Explaining the importance of active listening in conflict resolution.",
    "Describing the role of a growth mindset in professional success.",
    "Articulating the concept of servant leadership.",
    "Explaining how to handle ambiguity in a professional environment.",
    "Describing the impact of corporate social responsibility on brand image.",
    "Articulating the importance of setting SMART career goals.",
    "Explaining the difference between efficiency and effectiveness.",
    "Describing the role of curiosity in lifelong professional learning.",
    "Articulating how delegation empowers a team.",
    "Explaining the importance of digital literacy in the modern workplace."
  ],

  // ── SITUATIONAL SPEAKING ─────────────────────────────────────────────────────
  // High-pressure real-world response scenarios
  situational: [
    "Handling an urgent project delay notification to a client.",
    "Responding to a critical defect discovered just before a product launch.",
    "Dealing with a sudden reduction in team budget mid-project.",
    "Addressing a conflict between two strong-willed team members.",
    "Managing a project scope change requested by a client at the last moment.",
    "Responding to a server outage during peak business hours.",
    "Handling a situation where a key team member suddenly resigns.",
    "Explaining a system failure to senior management under pressure.",
    "Dealing with a client who refuses to accept agreed deliverables.",
    "Managing team morale after a major project is cancelled.",
    "Responding to negative media coverage about your organisation.",
    "Handling a data breach notification responsibly.",
    "Dealing with a missed deadline that impacts a dependent team.",
    "Managing a resource crunch when multiple projects overlap.",
    "Responding to an irate customer calling for immediate escalation.",
    "Handling a situation where two colleagues take opposing ethical positions.",
    "Addressing a compliance violation discovered during an internal audit.",
    "Dealing with a vendor who cannot deliver on contractual commitments.",
    "Responding to unexpected negative feedback from senior leadership.",
    "Managing stakeholder expectations when a product is significantly delayed.",
    "Handling a situation where a competitor has launched a similar product first.",
    "Responding to a workplace harassment complaint as a manager.",
    "Dealing with an urgent requirement with no clear documentation.",
    "Handling a public relations crisis for your organisation.",
    "Addressing poor performance in a direct report compassionately.",
    "Managing a critical handover where documentation is missing.",
    "Responding to a situation where your proposal is rejected without explanation.",
    "Handling a miscommunication that has already caused a client complaint.",
    "Dealing with a situation where technology infrastructure fails during a demo.",
    "Responding to a co-worker who takes credit for your contribution.",
    "Managing the announcement of an unpopular organisational policy change.",
    "Handling a scenario where the project requirements are completely unclear.",
    "Responding to team burnout during an intensive delivery period.",
    "Dealing with an external audit request with very short notice.",
    "Handling a disagreement over technical architecture with the team lead.",
    "Responding to a situation where critical data has been accidentally deleted.",
    "Managing the fallout of a miscommunication in a public forum.",
    "Dealing with a partner organisation that is unresponsive.",
    "Handling a scenario where quality testing reveals multiple critical failures.",
    "Responding professionally when your idea is publicly criticised."
  ],

  // ── PRESENTATION PRACTICE ────────────────────────────────────────────────────
  // Structured keynote and pitch topics
  presentation: [
    "The Future of Renewable Energy in India",
    "Artificial Intelligence: Transforming Modern Industries",
    "The Importance of Cyber Security in Digital Organisations",
    "Designing User-Centric Digital Products",
    "The Business Case for a Four-Day Work Week",
    "Emotional Intelligence as a Core Leadership Skill",
    "Continuous Integration and DevOps: Why They Matter",
    "The Power of Big Data Analytics in Strategic Decision-Making",
    "Transitioning to Sustainable Business Practices",
    "Quantum Computing: What Businesses Need to Know Now",
    "Effective Communication Strategies for Distributed Teams",
    "The Role of Machine Learning in Modern Healthcare",
    "Building High-Performance Engineering Teams",
    "The Impact of Automation on the Future of Employment",
    "Data Privacy and Ethics in the Age of Artificial Intelligence",
    "The Rise of the Creator Economy",
    "Blockchain Beyond Cryptocurrency: Real-World Applications",
    "Strategies for Building an Inclusive Workplace Culture",
    "The Future of Mobile-First Commerce",
    "Smart Cities: Opportunities and Challenges",
    "Cultivating a Culture of Innovation in Large Organisations",
    "The Digital Transformation Journey of Traditional Industries",
    "Building Resilience in Organisational Leadership",
    "Personalisation at Scale: AI-Driven Customer Experiences",
    "The Strategic Importance of Open Source Software",
    "Understanding the Metaverse and its Business Implications",
    "The Future of Electric Vehicles and Smart Mobility",
    "Why Mental Health at Work is a Business Priority",
    "Agile Project Management: Beyond Software Development",
    "The Role of Storytelling in Effective Business Communication",
    "E-Learning Platforms: Disrupting Traditional Education",
    "The Global Impact of Climate Tech Startups",
    "Leveraging Social Media for Brand Building",
    "The Future of Fintech and Digital Banking",
    "Reskilling and Upskilling for the Workforce of Tomorrow",
    "Designing Accessible Products for Diverse Users",
    "Corporate Social Responsibility: From Compliance to Culture",
    "The Science of Habit Formation and Productivity",
    "Understanding Gen Z: The Next Generation Workforce",
    "Measuring What Matters: Key Metrics for Business Success"
  ],

  // ── LEADERSHIP PRACTICE ───────────────────────────────────────────────────────
  // Leadership scenarios and vision-setting topics
  leadership: [
    "Inspiring a team after falling short of a quarterly target.",
    "Setting a compelling long-term vision for your department.",
    "Delegating critical responsibilities to develop your team's capacity.",
    "Navigating your team through a major organisational restructure.",
    "Championing a culture of psychological safety and open dialogue.",
    "Mentoring a high-potential team member toward a leadership role.",
    "Resolving a persistent conflict between two senior team members.",
    "Leading a cross-functional team with no direct authority.",
    "Making a high-stakes decision with incomplete and ambiguous data.",
    "Driving innovation and experimentation within a risk-averse culture.",
    "Managing a team distributed across multiple time zones.",
    "Turning around a team with low morale and poor performance.",
    "Building trust quickly when joining a new team as a leader.",
    "Handling a situation where your leadership style is questioned.",
    "Communicating a difficult decision transparently to your team.",
    "Creating a sustainable performance culture in your organisation.",
    "Advocating for your team's needs with senior leadership.",
    "Balancing short-term delivery pressure with long-term team health.",
    "Leading a team through uncertainty and rapid market change.",
    "Developing a succession plan for critical roles in your team.",
    "Driving alignment across teams with conflicting priorities.",
    "Establishing clear accountability without micromanaging.",
    "Celebrating team successes in a meaningful and inclusive way.",
    "Fostering a learning culture where failure is a source of insight.",
    "Creating development plans tailored to each team member.",
    "Leading an organisation-wide change management initiative.",
    "Navigating a situation where the right path conflicts with a directive.",
    "Building strong peer relationships with other department leaders.",
    "Empowering junior leaders to make independent decisions.",
    "Establishing ethical standards in a competitive team environment.",
    "Handling a situation where a team member's personal issues affect performance.",
    "Leading a team takeover from a previous well-respected manager.",
    "Driving adoption of a new process that the team resists.",
    "Handling team performance issues transparently and fairly.",
    "Responding to a leadership crisis caused by an unexpected external event.",
    "Building a diverse hiring pipeline and inclusive onboarding process.",
    "Creating a culture of recognition and continuous positive reinforcement.",
    "Navigating resource conflicts in a matrix organisation.",
    "Leading a team toward a bold goal with limited historical precedent.",
    "Reflecting on a leadership failure and what you would do differently."
  ],

  // ── CONFIDENCE PRACTICE ───────────────────────────────────────────────────────
  // Scenarios requiring assertive and composed delivery
  confidence: [
    "Pitching your personal career vision to a panel of senior leaders.",
    "Presenting your biggest project at a company-wide all-hands meeting.",
    "Asserting your perspective firmly but respectfully in a group debate.",
    "Requesting a well-deserved promotion in a formal conversation with your manager.",
    "Defending your design or technical decisions to a skeptical audience.",
    "Delivering a keynote speech at a campus or industry event.",
    "Responding to an unexpected hostile question during a live presentation.",
    "Standing by an unpopular decision you believe is correct.",
    "Introducing yourself with impact at an industry networking event.",
    "Pitching your startup idea to a group of experienced investors.",
    "Answering a question you don't know the full answer to gracefully.",
    "Delivering an impromptu two-minute speech with no preparation.",
    "Representing your team's position in a cross-department negotiation.",
    "Asserting your boundaries professionally with a demanding colleague.",
    "Responding to public criticism of your project with composure.",
    "Leading a difficult conversation about underperformance.",
    "Speaking first in a group discussion to set the direction.",
    "Challenging a flawed assumption in a senior leadership meeting.",
    "Accepting an award or achievement publicly with authentic gratitude.",
    "Giving a vote of thanks at the conclusion of a major event.",
    "Re-presenting a rejected proposal with renewed conviction.",
    "Speaking confidently about an area where you are still developing.",
    "Correcting a misconception about your work in front of stakeholders.",
    "Demonstrating calm authority during a team crisis.",
    "Saying no confidently when asked to take on work beyond your capacity.",
    "Presenting quarterly results that are below expectations.",
    "Expressing a bold and contrarian viewpoint in a professional setting.",
    "Volunteering to lead a high-risk, high-visibility project.",
    "Giving direct feedback to a peer whose work is below standard.",
    "Speaking up when you witness something unfair or unethical at work.",
    "Asking a thought-provoking question in a large group setting.",
    "Reclaiming control of a presentation after an unexpected disruption.",
    "Admitting a mistake to your team openly and proposing how to fix it.",
    "Articulating your value proposition in a salary negotiation.",
    "Facilitating a heated discussion and keeping it productive.",
    "Expressing a strong opinion on a controversial professional topic.",
    "Confidently presenting technical content to a non-technical audience.",
    "Owning the room during a panel discussion with experienced professionals.",
    "Delivering a frank and honest assessment when asked for your opinion.",
    "Engaging a disinterested or distracted audience and recapturing attention."
  ],

  // ── PRONUNCIATION PRACTICE ───────────────────────────────────────────────────
  // Passages and phrases targeting phonetic clarity and articulation
  pronunciation: [
    "Articulating business and professional vocabulary with clear word stress.",
    "Reading a formal corporate communication aloud with correct intonation.",
    "Pronouncing commonly mispronounced English words in a business context.",
    "Delivering a structured paragraph on technology with clear consonant sounds.",
    "Articulating numbers, statistics, and data points in a presentation.",
    "Pronouncing international city and country names correctly.",
    "Reading a product description with emphasis on key selling points.",
    "Articulating multi-syllable academic and professional terms precisely.",
    "Delivering a formal apology statement with appropriate tone and pacing.",
    "Reading a news headline and developing it into a clear spoken paragraph.",
    "Pronouncing commonly confused word pairs: affect/effect, accept/except.",
    "Articulating a legal or contractual clause with precision.",
    "Delivering a weather forecast-style monologue with clear diction.",
    "Pronouncing medical and scientific terminology with confidence.",
    "Articulating technical acronyms and abbreviations used in IT industries.",
    "Reading a financial report summary with appropriate stress and pausing.",
    "Pronouncing names and terms from diverse cultural backgrounds respectfully.",
    "Delivering a sports commentary-style narration with clear articulation.",
    "Articulating transition phrases used in formal speeches and presentations.",
    "Pronouncing tongue-twisters to develop phonetic agility and clarity.",
    "Delivering a product launch announcement with precise and energetic diction.",
    "Articulating soft-spoken vs. projected speech at different audience sizes.",
    "Reading a policy document paragraph with steady pacing and clarity.",
    "Pronouncing words with silent letters correctly (e.g., colonel, receipt).",
    "Delivering directions or instructions with crisp and unambiguous articulation.",
    "Pronouncing Indian English with a more neutral and internationally clear accent.",
    "Articulating question intonation patterns in professional contexts.",
    "Delivering a dramatic literary passage with expressive and clear speech.",
    "Pronouncing commonly borrowed words from French and Latin correctly.",
    "Articulating a list of ingredients or steps in a recipe with precision.",
    "Delivering the words to a well-known poem or speech with clear diction.",
    "Pronouncing technical software and programming terms naturally.",
    "Articulating airport and travel announcement-style spoken phrases.",
    "Delivering a mock television interview answer with confident pronunciation.",
    "Pronouncing words that differ between British and American English.",
    "Articulating emphasis and de-emphasis for rhetorical effect.",
    "Delivering a call-to-action sales pitch with energy and clear consonants.",
    "Pronouncing the English alphabet, numbers, and dates unambiguously.",
    "Articulating proper nouns and brand names used in global business.",
    "Delivering a personal statement paragraph with measured pacing and clarity."
  ],

  // ── GROUP DISCUSSION ─────────────────────────────────────────────────────────
  // GD topics used in campus placements and corporate hiring
  groupDiscussion: [
    "Artificial Intelligence: Will It Create More Jobs or Eliminate Them?",
    "Social Media: Boon or Bane for Society?",
    "Online Education vs Classroom Education: Which is Better?",
    "Work From Home vs Work From Office: What is the Future?",
    "Should Companies Prioritise Skills Over Degrees in Hiring?",
    "The Importance of Soft Skills in Career Success",
    "Technology and the Erosion of Human Relationships",
    "Four-Day Work Week: Pros and Cons",
    "AI in Education: Opportunity or Risk?",
    "Climate Change: Corporate Responsibility vs Individual Action",
    "Is the Gig Economy Good for Workers?",
    "Impact of Digital Payments on Financial Inclusion",
    "Should Voting Be Made Compulsory in India?",
    "Is Privacy Possible in the Age of Big Data?",
    "Cryptocurrency: The Currency of the Future or a Speculative Bubble?",
    "Should College Education Be Free?",
    "The Role of Youth in Driving Social Change",
    "Is Social Media Making People More Politically Aware or More Polarised?",
    "Electric Vehicles: Are They Truly Sustainable?",
    "Is Competition Healthy for Students and Professionals?",
    "Globalisation: Benefits and Drawbacks for Developing Nations",
    "Should Smartphones Be Banned in Schools?",
    "Impact of Influencer Culture on Consumer Behaviour",
    "Importance of Mental Health Support in the Workplace",
    "Should Animal Testing for Medical Research Be Allowed?",
    "The Rise of E-Commerce and Its Impact on Local Businesses",
    "Universal Basic Income: A Practical Solution?",
    "Gender Equality in the Workplace: How Much Progress Has Been Made?",
    "Is Space Exploration a Worthwhile Investment for Humanity?",
    "Automation: Threat to Blue-Collar Workers or Opportunity for Growth?",
    "Nuclear Energy: A Sustainable Solution to the Energy Crisis?",
    "Should Social Media Platforms Be Held Accountable for Misinformation?",
    "Brain Drain: How Can India Retain Its Talent?",
    "Impact of Fast Fashion on the Environment",
    "Is Multitasking a Productive Skill or a Myth?",
    "Ethical AI: Who Is Responsible When AI Systems Fail?",
    "Should Professional Athletes Be Considered Role Models?",
    "The Impact of Streaming Platforms on Traditional Cinema",
    "Startups vs Established Companies: Which Is the Better Career Choice?",
    "Is Standardised Testing a Fair Measure of Student Intelligence?",
    "Sustainable Development: Economic Growth vs Environmental Protection",
    "Should the Minimum Wage Be Significantly Increased?",
    "The Future of Space Tourism: Luxury or Necessity?",
    "Remote Work: How Has It Changed Organisational Culture?",
    "Digital Literacy: Should It Be a Core Subject in Schools?"
  ],

  // ── DEBATE ────────────────────────────────────────────────────────────────────
  // Topics that naturally support FOR and AGAINST arguments
  debate: [
    "AI will replace more jobs than it creates in the next decade.",
    "Social media does more harm than good to young people.",
    "College degrees are no longer essential for a successful career.",
    "Remote work is more productive than working from an office.",
    "Smartphones should be completely banned in schools and colleges.",
    "AI should be integrated into all school curriculums immediately.",
    "Standardised exams are not a fair or effective measure of ability.",
    "Companies should always prioritise demonstrated skills over formal degrees.",
    "The four-day work week should become the global standard.",
    "Technology is making younger generations less socially capable.",
    "Cryptocurrency should replace traditional paper currencies.",
    "Space exploration is a waste of public money.",
    "Homework should be abolished in primary and secondary education.",
    "Nuclear energy is the safest and most sustainable solution to the energy crisis.",
    "Financial success is the most important measure of a meaningful career.",
    "Social media influencers have a damaging influence on young people.",
    "Online shopping is permanently superior to in-person retail.",
    "Competitive video gaming should be considered a legitimate sport.",
    "Electric vehicles are not yet a realistic solution for mass adoption.",
    "Voting should be mandatory for all eligible citizens.",
    "Generative AI is a threat to human creativity.",
    "E-learning will eventually make physical universities obsolete.",
    "Complete data privacy is impossible in the modern digital age.",
    "Academic competition produces more harm than benefit for students.",
    "Automation will ultimately improve quality of life for workers.",
    "Public transport should be made completely free for all citizens.",
    "All animal testing for scientific and medical purposes should be banned.",
    "Standardised tests are fundamentally biased against disadvantaged groups.",
    "Modern advertising is inherently manipulative and should be regulated.",
    "The concept of a monarchy has no place in the twenty-first century.",
    "Genetically modified food is safe and necessary for global food security.",
    "Fast fashion brands should be taxed according to their environmental damage.",
    "A person's online reputation matters more than their in-person one.",
    "Smart virtual assistants are a significant invasion of personal privacy.",
    "Governments should have full authority to regulate content on social media.",
    "Working mothers face unfair disadvantages that fathers do not.",
    "Universal basic income is economically feasible and socially necessary.",
    "Homeschooling produces better-rounded individuals than traditional schools.",
    "Professional athletes are paid excessively relative to their social value.",
    "Developing countries have more to lose than gain from rapid globalisation.",
    "The legal voting age should be lowered to sixteen.",
    "Artificial intelligence will eventually surpass human intelligence.",
    "Zoos are fundamentally unethical and should be phased out.",
    "The death penalty should be abolished in all countries worldwide.",
    "Mandatory military service produces more capable and responsible citizens."
  ]

};
